### ISSUE TITLE
Provide skeleton bot for testing

### ISSUE THREAD

**Issue by MattIPv4** [TheYogscast/Jaffa3Community#3]
Currently, there isn't a way for contributors to actually test their code before it is loaded into the production JaffaMod bot as this repository contains none of the actual bot code.

hilst, obviously, the full JaffaMod bot is private, it'd be super useful to have a skeleton version of the core bot in this repo, so that modules can be tested in development.

**Comment by Akhawais** [comment]
Skeleton repo now available - please contact Akhawais#0001 in https://discord.gg/yogscast
